# Basic AeroSpace config
# Docs: https://nikitabobko.github.io/AeroSpace/

# Keybindings (hjkl navigation, move, resize, fullscreen)
[mode.main.binding]
alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"

alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"

alt-ctrl-h = "resize width -50"
alt-ctrl-l = "resize width +50"
alt-ctrl-j = "resize height -50"
alt-ctrl-k = "resize height +50"

# Fullscreen (AeroSpace expects on|off)
alt-f = "fullscreen on"
alt-shift-f = "fullscreen off"

# Reload AeroSpace configuration
alt-r = "reload-config"

# Fully restart AeroSpace (quit + relaunch)
# Requires Accessibility permissions to be already granted
alt-shift-r = "exec-and-forget sh -lc 'osascript -e \"tell application \\\"AeroSpace\\\" to quit\"; sleep 0.5; open -a AeroSpace'"
